version: '1.0.0'

services:

  database:
    image: postgres:16.1
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pendekindev
    ports:
      - 5432:5432

  cache:
    image: redis:7.2.4
    ports:
      - 6379:6379